# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
- task: NodeTool@0
  inputs:
   versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
     npm install
  displayName: 'npm install and test'

- script: |
    wget https://github.com/github/codeql-action/releases/lastest/download/codeql-runner-linux
    chmode +x codeql-runner-linux
  displayName: 'Get lastest CodeQL package. Install on Agent'

- script: |
    ./codeql-runner-linux init \
    --repository fpt-hienpnb/CodeScanNodeJS.git \
    --github-url https://github.com/ \
    --github-auth $GITHUB_PAT \
    --config-file .github/codeql-config.yml
  displayName: 'Initialize CodeQL Exeutable and create a CodeQL DB'

- script: |
    ./codeql-runner-linux analyze \
    --repository fpt-hienpnb/CodeScanNodeJS.git \
    --github-url https://github.com \
    --github-auth $GITHUB_PAT \
    --commit $(Build.SourceVersion) \
    ref $(Build.SourceBranch)
  displayName: 'Popular the CodeQL runner DB. analyze them, and upload result to Github'
